// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeJPRnkLsYBjSW7akJM32wHBaxRJUPDUc',
    appId: '1:931422818625:web:e588908399db34386951c0',
    messagingSenderId: '931422818625',
    projectId: 'vikas-1cca9',
    authDomain: 'vikas-1cca9.firebaseapp.com',
    databaseURL: 'https://vikas-1cca9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vikas-1cca9.appspot.com',
    measurementId: 'G-MPBB11TC1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7oy9B5GQivWOB5g02jrItEEhP_ET2Q1k',
    appId: '1:931422818625:android:2b39b4ea70b16e996951c0',
    messagingSenderId: '931422818625',
    projectId: 'vikas-1cca9',
    databaseURL: 'https://vikas-1cca9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vikas-1cca9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUVup_nttxoaKaiRoKI5kcz05mFEaDpjw',
    appId: '1:931422818625:ios:abfcccc9654f13286951c0',
    messagingSenderId: '931422818625',
    projectId: 'vikas-1cca9',
    databaseURL: 'https://vikas-1cca9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vikas-1cca9.appspot.com',
    iosClientId: '931422818625-0rj6icbluqt6a4cldn6qkkmhdv48n8r8.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomcloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUVup_nttxoaKaiRoKI5kcz05mFEaDpjw',
    appId: '1:931422818625:ios:c2394aa649fd7f4d6951c0',
    messagingSenderId: '931422818625',
    projectId: 'vikas-1cca9',
    databaseURL: 'https://vikas-1cca9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vikas-1cca9.appspot.com',
    iosClientId: '931422818625-f15u31na64dg0ss8lgpc7g39ju29qdcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomcloneApp.RunnerTests',
  );
}
